### PR TITLE
firebase setup

### PR DESCRIPTION
**Pull request by KatKowalik**
## What type of PR is this? (check all applicable)

- [ ] 🥝 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [X] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] ⏩ Revert

## Description
Added firebase setup to the project and refactored code for FAQ page and About us page. Now the data for both pages is pulled from firestore.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📜 CONTRIBUTING.md
- [ ] 📜 PULL_REQUEST_TEMPLATE.md
- [x] ✖️ no documentation needed

## Added tests?

- [ ] ✔️ yes
- [ ] ✖️ no, testing will be added later
- [x] ✖️ no, because they aren't needed
- [ ] ❓ no, because I need help

## How to test...
N/A

### CODE REVIEW

**Review by mpa-mxiang — CHANGES_REQUESTED** [review]
## Project Status: CHANGES REQUIRED :recycle: 
Hi @KatKowalik  , 

Good job so far!
Thank you for requiring me to review but there is an issue that you still need to work on to go to the next project but you are almost there!


## Highlights
- Professional README file :heavy_check_mark: 
- Good PR title and Description :heavy_check_mark: 

## Required Changes ♻️
- It shows me "Site Not Found" when I review it :(
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by mpa-mxiang** [comment]
I saw the link was working twice but not anymore, so maybe check it again to see if there are any possible issues :)

**Review by mpa-mxiang — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @KatKowalik   :wave: 
 
Your project is complete now!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 👏🏻



:heavy_check_mark: Readme is professional.
:heavy_check_mark: Descriptive pull request.
:heavy_check_mark: Meaningful commit message.
:heavy_check_mark: Follow gitflow

## Optional suggestions 🤷‍♂️

- [ ] ***[Optional]*** Leave a comment for this PR to show that Netify's deployment is connected with Firebase successfully.


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [Mail](mailto:max997123@gmail.com) or ask any question at Slack, `Name: Jiachun Xiang`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

**Review by TanyaPina — APPROVED** [review]
Looking great! As always, thank you for the awesome work 😊

**Pull request merged**
